var userClickedPattern = [];
var gamePattern = [];
var buttonColors= ["red","blue", "green", "yellow"];

var randomNumber;
var level = -1;
var firstKeyPress = true;
var lastIndex = -1;
//For starting the game with key press
function startGame(){
    firstKeyPress=true;
    userClickedPattern = [];
    gamePattern=[];
    level = -1;
    $("#level-title").text("Press A Key to Start");
    $(document).keypress(()=>{
        if(firstKeyPress){
            nextSequence();
            firstKeyPress=false;
        }
    });
}
startGame();


//NextSequence generated by random number
function nextSequence(){
    userClickedPattern = [];
    level++;
    var x = (level).toString();
    $("#level-title").text("Level " + x);

    randomNumber = Math.floor(Math.random()*4);
    var randomChosenColor = buttonColors[randomNumber];
    gamePattern.push(randomChosenColor);

    $("#"+randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColor);
};



//Playsound function to play sound on every click and nextsequence
function playSound(name){
    var sound = new Audio("sounds/"+name+".mp3");
    sound.play();
}


//Click event listener
$(".btn").click((e)=>{
    var Target = e.target;
    playSound(Target.classList[1]);
    var userChosenColor = Target.id;
    userClickedPattern.push(userChosenColor);
    animatePress(userChosenColor);
    checkSequence(userClickedPattern.length-1);
});


//add animation class to pressed button
function animatePress(currentColor){
    $("#"+currentColor).addClass("pressed");
    setTimeout(()=>{
        $("#"+currentColor).removeClass("pressed");
    }, 100);
}

//check the user sequence with game pattern and upgrade the level

function checkSequence(currentLevel){
    if(gamePattern[currentLevel] === userClickedPattern[currentLevel]){
        if(userClickedPattern.length === gamePattern.length){
            setTimeout(nextSequence, 1000);
        }
    }
    else{
        //if there is wrong sequence, then display game over and ask to press any key to restart the game
        playSound("wrong");
        $("body").addClass("game-over");
        $("#level-title").text("Game Over, Press a key to restart");
        setTimeout(()=>{
            $("body").removeClass("game-over");
            startGame();
        }, 200);
        
    }

}








